version: '3.7'

services:
  api:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - network-api
      
  mysql-api:
    image: mysql:5.7
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_DATABASE=restaurante"
      - "MYSQL_USER=restaurante"
      - "MYSQL_PASSWORD=restaurante"
      - "MYSQL_ROOT_PASSWORD=restaurante"
    networks:
      - network-api

  php:
    build: .
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - network-api

networks:
  network-api:
    name: network_api