version: "3.7"
services:

  ## PHP-FPM Container ############
  php-fpm:
    build:
      context: ./
      dockerfile: Dockerfile
    image: php-fpm
    container_name: api-projeto-restaurante-php-fpm
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - api-projeto-restaurante-network
    depends_on:
      - mysql

  ## NGINX Container #############
  nginx:
    image: nginx:1.19-alpine
    container_name: api-projeto-restaurante-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api-projeto-restaurante-network
    depends_on:
      - php-fpm
      
  ## MySQL Container #############
  mysql:
    image: mysql:8.0
    container_name: api-projeto-restaurante-mysql
    volumes:
      - api-projeto-restaurante-db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_DATABASE=restaurante"
      - "MYSQL_USER=restaurante"
      - "MYSQL_PASSWORD=restaurante"
      - "MYSQL_ROOT_PASSWORD=restaurante"
    networks:
      - api-projeto-restaurante-network
      
networks:
  api-projeto-restaurante-network:
    driver: bridge
    name: network_api

volumes:
  api-projeto-restaurante-db:
    driver: local